# Generated by Django 3.2.3 on 2021-07-01 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_book_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': '著者', 'verbose_name_plural': '著者'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '本', 'verbose_name_plural': '本'},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'verbose_name': '出版社', 'verbose_name_plural': '出版社'},
        ),
    ]
